[linters]
  presets = [
    "comment",
    "complexity",
    "error",
    "format",
    "import",
    "metalinter",
    "module",
    "performance",
    "sql",
    "style",
    "test",
    "unused",
    ]
[run]
  skip-dirs = ["gen"]