version: 2
jobs:
  build_backend:
    docker:
      - image: cimg/go:1.14
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update;
            sudo apt-get install --no-install-recommends --no-install-suggests libvips libvips-dev;

      - run:
          name: Build backend
          command: |
            cd harmony-server/;
            go get -v -t -d ./...;
            go fmt ./...;
            go vet ./...;
            go build;

      - store_artifacts:
          path: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/harmony-server/harmony-server
          destination: harmony-bin

workflows:
  version: 2
  build_all:
    jobs:
      - build_backend
