version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  build_backend:
    docker:
      - image: cimg/go:1.14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update;
            sudo apt-get install --no-install-recommends --no-install-suggests libvips libvips-dev;

      - run:
          name: Build backend
          command: |
            cd harmony-server/;
            go get -v -t -d ./...;
            go fmt ./...;
            go vet ./...;
            go build;

      - slack/notify:
            channel: "709945941096005742"
            color: '#42e2f4'
            message: This is a custom message notification
            
      - store_artifacts:
          path: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/harmony-server/harmony-server
          destination: harmony-bin
          
  build_frontend:
    docker:
      - image: cimg/node:12.16

    steps:
      - checkout

      - run:
          name: Build frontend
          command: |
            cd harmony-app/;
            npm install netlify-cli;
            yarn;
            CI=false yarn build;
            ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod --dir=build

      - store_artifacts:
          path: ~/project/harmony-app/build
          destination: harmony-app

workflows:
  version: 2
  build_all:
    jobs:
      - build_backend
      - build_frontend
