name: Update Legato service
on:
  push:
    branches:
      - main
jobs:
  update:
    name: Update Legato service
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "$SSH_KEY" > key'
        shell: bash
        env:
          SSH_KEY: ${{secrets.ACTIONS_SSH_KEY}}
      - run: 'echo "$KNOWN_HOSTS" > known_hosts'
        shell: bash
        env:
          KNOWN_HOSTS: ${{secrets.ACTIONS_SSH_KNOWN_HOSTS}}
      - run: 'ssh -i key -o UserKnownHostsFile=known_hosts "root@$SSH_HOST" systemctl start update-legato'
        shell: bash
        env:
          SSH_HOST: ${{secrets.ACTIONS_SSH_HOST}}
